### ISSUE TITLE
DesktopFileChooser does not release resouces used by fileDialog

### ISSUE THREAD

**Issue by Anton-Samarskyi** [spookygames/gdx-nativefilechooser#9] opened 2024-02-25 16:02 UTC
I tried to use DesktopFileChooser in my app and noticed that some thread is still present after application is closed. I figured out that it's due to missing dispose call on fileDialog in DesktopFileChooser.

The fix looks pretty simple (I checked it locally):
`fileDialog.dispose();`
But better to do that in finally block.

**Comment by Anton-Samarskyi** [comment] 2024-02-25 16:13
Please take a look:
https://github.com/spookygames/gdx-nativefilechooser/pull/10

**Comment by arthurtemple** [comment] 2024-12-30 20:06
Thanks a lot for your contribution!

The issue is fixed in [version 2.4.0](https://github.com/spookygames/gdx-nativefilechooser/releases/tag/2.4.0).

**Closed as completed by arthurtemple** 2024-12-30 20:06 UTC
