### ISSUE TITLE
Broken with LibGDX 1.12.0

### ISSUE THREAD

**Issue by tylerhasman** [spookygames/gdx-nativefilechooser#7] opened 2023-10-24 07:13 UTC
Getting this error with LibGDX 1.12.0 on Desktop (windows).

com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: org.lwjgl.util.nfd.NativeFileDialog.NFD_OpenDialog(Ljava/lang/CharSequence;Ljava/lang/CharSequence;Lorg/lwjgl/PointerBuffer;)I
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at rpg.editor.EditorLauncher.main(EditorLauncher.java:57)
Caused by: java.lang.NoSuchMethodError: org.lwjgl.util.nfd.NativeFileDialog.NFD_OpenDialog(Ljava/lang/CharSequence;Ljava/lang/CharSequence;Lorg/lwjgl/PointerBuffer;)I
	at games.spooky.gdx.nativefilechooser.desktop.DesktopFileChooser.chooseFile(DesktopFileChooser.java:68)
	at rpg.editor.gui.DatabaseRenderer.renderField(DatabaseRenderer.java:159)
	at rpg.editor.gui.DatabaseRenderer.renderDataEntry(DatabaseRenderer.java:80)
	at rpg.editor.EditorGame.render(EditorGame.java:774)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	... 1 more

Seems like the problem is that gdx-nativefilechooser is using LWJGL 3.3.1 while LibGDX now uses 3.3.3

**Comment by arthurtemple** [comment] 2024-12-30 20:06
Thanks for the report. The issue is fixed in [version 2.4.0](https://github.com/spookygames/gdx-nativefilechooser/releases/tag/2.4.0).

**Closed as completed by arthurtemple** 2024-12-30 20:06 UTC
